#!/bin/csh -f
#
#  Wrapper around Cola's configure to make it work with the OpenGRADS supplibs
#

setenv ARCH `uname -s`

if ( $?SUPPLIBS ) then
   echo Using OpenGRADS SUPPLIBS from $SUPPLIBS
else
   echo OpenGRADS environment variable SUPPLIBS not set
   exit 1
endif

set here = `pwd`
set bin = $here/bin
set lib = $here/bin/gex

mkdir -p $bin
mkdir -p $lib

if ( $ARCH == 'Darwin' ) then
      setenv LIBS '-L/usr/X11/lib -lXaw3d -lXmu -lXt -lXext -lXpm  -lSM -lICE -lX11 -liconv'
endif

(cd cola; ./configure \
                      --with-gadap \
		      --with-gui \
		      --with-opengrads \
		      --bindir=$bin \
		      --libdir=$lib \
)	      
		      


